#!/usr/bin/env python3
"""Add new i18n keys for: progress areas, AI chips, snapshot stat labels,
ParentActivitiesPanel UI chrome, and related strings."""

NEW_KEYS = {
  'en': {
    # Progress area labels
    'progress_area_reading':   'Reading',
    'progress_area_numeracy':  'Numeracy',
    'progress_area_writing':   'Writing',
    'progress_area_wellbeing': 'Wellbeing',
    'progress_area_creative':  'Creative',
    'progress_area_science':   'Science',
    # Snapshot stat labels
    'snapshot_stars_label':   'Stars',
    'snapshot_correct_label': 'Correct',
    'snapshot_streak_label':  'Day Streak',
    # Snapshot help tips
    'snapshot_help_maths':   'Try counting objects around the house together — small steps build big confidence!',
    'snapshot_help_english': 'Reading aloud together for just 10 minutes a day makes a huge difference.',
    'snapshot_help_science': 'Science questions come alive when you explore simple experiments at home!',
    'snapshot_help_general': 'Exploring the world through books, maps, or documentaries boosts general knowledge fast.',
    'snapshot_weakest_suffix': 'has the fewest correct answers.',
    # AI chips (Sparky parent quick-prompts)
    'ai_chip_1': 'How do I support SEN readers?',
    'ai_chip_2': 'What KS2 maths topics are hardest?',
    'ai_chip_3': 'Recommend an activity for age 5',
    # ParentActivitiesPanel UI chrome
    'tier_activities_month': '{n} activities this month',
    'tier_next_label':       'Next:',
    'quiz_modal_progress':   'Question {n} of {total}',
    'quiz_modal_wrong':      'The answer is: {answer}',
    'quiz_modal_earned':     'You earned {reward}!',
    'article_modal_next':    'Next',
    'article_modal_finish':  'Finish',
    'confirm_self_label':    'I confirm I have completed this activity',
    'confirm_joint_label':   'I confirm we both completed: {title}',
    'confirm_child_label':   'My child has completed their part',
    'reward_pill_both':      'Child earns {n} stars · You earn: {reward}',
    'claim_reward_close':    'Claim Reward & Close',
    'steps_confirm':         'We both completed this walk together',
    'checklist_found':       '{n} of {total} found',
    'guided_step_label':     'Step {n} of {total}',
    'guided_confirm':        'We completed this mindfulness together',
    'text_label_drawing':    "Describe your child's drawing and add a caption:",
    'text_label_kind':       'Describe the kind act your child performed:',
    'text_confirm':          'We both confirm this was completed',
    'story_confirm':         'We created this story together',
    'story_preview_intro':   'Your story: Once upon a time,',
    'rating_topic_label':    'Your child chose to teach you about:',
    'rating_confirm':        'My child taught me about this topic today',
    'phrases_count':         '{n} of {total} practised',
    'phrases_say_it':        'Say it:',
    'phrases_confirm':       'We both practised these phrases together',
    'mystery_next_clue':     'Next Clue →',
    'mystery_confirm':       'We solved this mystery together',
    'wallet_active_count':   '{n} active',
    'wallet_expires_day':    'Expires in {n} day',
    'wallet_expires_days':   'Expires in {n} days',
    'cap_solo_label':        'Solo activities: {n}% of 30% cap used',
    'cap_combined_label':    'Combined (A+B): {n}% of 40% cap used',
    'joint_parent_label':    'Parent',
    'joint_child_label':     'Child',
    'parent_act_supporting': 'supporting {name}',
    'module_desc_a':         'Complete these solo activities to better support your child — and earn discounts along the way.',
    'module_desc_b':         'Do these activities together with {name}. Both must confirm to unlock rewards for both of you.',
    'module_desc_c':         'Help your child build real-world habits. Tick the checkbox to confirm each challenge.',
    'module_desc_d':         'Extended activities across Wellbeing, Creative, Values, and Cultural categories.',
  },
  'cy': {
    'progress_area_reading':   'Darllen',
    'progress_area_numeracy':  'Rhifedd',
    'progress_area_writing':   'Ysgrifennu',
    'progress_area_wellbeing': 'Lles',
    'progress_area_creative':  'Creadigol',
    'progress_area_science':   'Gwyddoniaeth',
    'snapshot_stars_label':   'Sêr',
    'snapshot_correct_label': 'Cywir',
    'snapshot_streak_label':  'Diwrnod Llinyn',
    'snapshot_help_maths':   'Ceisiwch gyfrif gwrthrychau o amgylch y tŷ gyda\'ch gilydd — mae camau bach yn adeiladu hyder mawr!',
    'snapshot_help_english': 'Mae darllen yn uchel gyda\'ch gilydd am ddim ond 10 munud y dydd yn gwneud gwahaniaeth mawr.',
    'snapshot_help_science': 'Mae cwestiynau gwyddoniaeth yn dod yn fyw pan fyddwch chi\'n archwilio arbrofion syml gartref!',
    'snapshot_help_general': 'Mae archwilio\'r byd trwy lyfrau, mapiau, neu raglenni dogfen yn hybu gwybodaeth gyffredinol.',
    'snapshot_weakest_suffix': 'sydd â\'r nifer lleiaf o atebion cywir.',
    'ai_chip_1': 'Sut ydw i\'n cefnogi darllenwyr ag AAA?',
    'ai_chip_2': 'Pa bynciau maths CA2 sydd anoddaf?',
    'ai_chip_3': 'Argymhell weithgaredd ar gyfer oedran 5',
    'tier_activities_month': '{n} gweithgaredd y mis hwn',
    'tier_next_label':       'Nesaf:',
    'quiz_modal_progress':   'Cwestiwn {n} o {total}',
    'quiz_modal_wrong':      'Yr ateb yw: {answer}',
    'quiz_modal_earned':     'Fe wnaethoch ennill {reward}!',
    'article_modal_next':    'Nesaf',
    'article_modal_finish':  'Gorffen',
    'confirm_self_label':    'Rwy\'n cadarnhau fy mod wedi cwblhau\'r gweithgaredd hwn',
    'confirm_joint_label':   'Rwy\'n cadarnhau ein bod ni\'n dau wedi cwblhau: {title}',
    'confirm_child_label':   'Mae fy mhlentyn wedi cwblhau eu rhan nhw',
    'reward_pill_both':      'Plentyn yn ennill {n} seren · Chi\'n ennill: {reward}',
    'claim_reward_close':    'Hawlio Gwobr & Cau',
    'steps_confirm':         'Fe gwnaethom ni\'r daith hon gyda\'n gilydd',
    'checklist_found':       '{n} o {total} wedi\'u canfod',
    'guided_step_label':     'Cam {n} o {total}',
    'guided_confirm':        'Fe gwnaethom ni\'r ymarfer ymwybyddiaeth ofalgar hwn gyda\'n gilydd',
    'text_label_drawing':    'Disgrifiwch lun eich plentyn ac ychwanegwch deitl:',
    'text_label_kind':       'Disgrifiwch y weithred garedig a wnaeth eich plentyn:',
    'text_confirm':          'Rydym ni\'n dau yn cadarnhau bod hyn wedi\'i gwblhau',
    'story_confirm':         'Fe greodd ni\'r stori hon gyda\'n gilydd',
    'story_preview_intro':   'Eich stori: Un tro,',
    'rating_topic_label':    'Dewisodd eich plentyn ddysgu i chi am:',
    'rating_confirm':        'Dysgodd fy mhlentyn i mi am y pwnc hwn heddiw',
    'phrases_count':         '{n} o {total} wedi\'u hymarfer',
    'phrases_say_it':        'Dywedwch:',
    'phrases_confirm':       'Fe ymarferodd y ddau ohonom yr ymadroddion hyn gyda\'n gilydd',
    'mystery_next_clue':     'Cliw Nesaf →',
    'mystery_confirm':       'Fe datrysasom ni\'r dirgelwch hwn gyda\'n gilydd',
    'wallet_active_count':   '{n} actif',
    'wallet_expires_day':    'Yn dod i ben mewn {n} diwrnod',
    'wallet_expires_days':   'Yn dod i ben mewn {n} diwrnod',
    'cap_solo_label':        'Gweithgareddau unigol: {n}% o\'r cap 30% wedi\'i ddefnyddio',
    'cap_combined_label':    'Cyfun (A+B): {n}% o\'r cap 40% wedi\'i ddefnyddio',
    'joint_parent_label':    'Rhiant',
    'joint_child_label':     'Plentyn',
    'parent_act_supporting': 'yn cefnogi {name}',
    'module_desc_a':         'Cwblhewch y gweithgareddau unigol hyn i gefnogi eich plentyn yn well — ac ennill gostyngiadau.',
    'module_desc_b':         'Gwnewch y gweithgareddau hyn gyda {name}. Rhaid i\'r ddau gadarnhau i ddatgloi gwobrau.',
    'module_desc_c':         'Helpwch eich plentyn i feithrin arferion byd go iawn. Ticiwch y blwch i gadarnhau.',
    'module_desc_d':         'Gweithgareddau estynedig ar draws Lles, Creadigol, Gwerthoedd a Diwylliannol.',
  },
  'fr': {
    'progress_area_reading':   'Lecture',
    'progress_area_numeracy':  'Numératie',
    'progress_area_writing':   'Écriture',
    'progress_area_wellbeing': 'Bien-être',
    'progress_area_creative':  'Créativité',
    'progress_area_science':   'Sciences',
    'snapshot_stars_label':   'Étoiles',
    'snapshot_correct_label': 'Correct',
    'snapshot_streak_label':  'Jours consécutifs',
    'snapshot_help_maths':   'Essayez de compter des objets ensemble à la maison — les petits pas construisent une grande confiance !',
    'snapshot_help_english': 'Lire à voix haute ensemble pendant seulement 10 minutes par jour fait une énorme différence.',
    'snapshot_help_science': 'Les questions scientifiques prennent vie quand vous explorez des expériences simples à la maison !',
    'snapshot_help_general': 'Explorer le monde à travers des livres, des cartes ou des documentaires stimule rapidement la culture générale.',
    'snapshot_weakest_suffix': 'a le moins de bonnes réponses.',
    'ai_chip_1': 'Comment soutenir les lecteurs ayant des besoins particuliers ?',
    'ai_chip_2': 'Quels sujets de maths sont les plus difficiles ?',
    'ai_chip_3': 'Recommandez une activité pour un enfant de 5 ans',
    'tier_activities_month': '{n} activités ce mois',
    'tier_next_label':       'Suivant :',
    'quiz_modal_progress':   'Question {n} sur {total}',
    'quiz_modal_wrong':      'La réponse est : {answer}',
    'quiz_modal_earned':     'Vous avez gagné {reward} !',
    'article_modal_next':    'Suivant',
    'article_modal_finish':  'Terminer',
    'confirm_self_label':    'Je confirme avoir terminé cette activité',
    'confirm_joint_label':   'Je confirme que nous avons tous les deux terminé : {title}',
    'confirm_child_label':   'Mon enfant a terminé sa partie',
    'reward_pill_both':      'Enfant gagne {n} étoiles · Vous gagnez : {reward}',
    'claim_reward_close':    'Réclamer la récompense & fermer',
    'steps_confirm':         'Nous avons tous les deux terminé cette promenade ensemble',
    'checklist_found':       '{n} sur {total} trouvés',
    'guided_step_label':     'Étape {n} sur {total}',
    'guided_confirm':        'Nous avons terminé cette session de pleine conscience ensemble',
    'text_label_drawing':    'Décrivez le dessin de votre enfant et ajoutez une légende :',
    'text_label_kind':       'Décrivez l\'acte gentil accompli par votre enfant :',
    'text_confirm':          'Nous confirmons tous les deux que c\'est terminé',
    'story_confirm':         'Nous avons créé cette histoire ensemble',
    'story_preview_intro':   'Votre histoire : Il était une fois,',
    'rating_topic_label':    'Votre enfant a choisi de vous apprendre :',
    'rating_confirm':        'Mon enfant m\'a appris ce sujet aujourd\'hui',
    'phrases_count':         '{n} sur {total} pratiqués',
    'phrases_say_it':        'Dites-le :',
    'phrases_confirm':       'Nous avons tous les deux pratiqué ces phrases ensemble',
    'mystery_next_clue':     'Indice suivant →',
    'mystery_confirm':       'Nous avons résolu ce mystère ensemble',
    'wallet_active_count':   '{n} actif(s)',
    'wallet_expires_day':    'Expire dans {n} jour',
    'wallet_expires_days':   'Expire dans {n} jours',
    'cap_solo_label':        'Activités solo : {n}% du cap de 30% utilisé',
    'cap_combined_label':    'Combiné (A+B) : {n}% du cap de 40% utilisé',
    'joint_parent_label':    'Parent',
    'joint_child_label':     'Enfant',
    'parent_act_supporting': 'soutenant {name}',
    'module_desc_a':         'Complétez ces activités solo pour mieux soutenir votre enfant — et gagnez des remises.',
    'module_desc_b':         'Faites ces activités ensemble avec {name}. Les deux doivent confirmer pour débloquer les récompenses.',
    'module_desc_c':         'Aidez votre enfant à développer de vraies habitudes du quotidien. Cochez pour confirmer.',
    'module_desc_d':         'Activités étendues en Bien-être, Créativité, Valeurs et Culture.',
  },
  'es': {
    'progress_area_reading':   'Lectura',
    'progress_area_numeracy':  'Numeración',
    'progress_area_writing':   'Escritura',
    'progress_area_wellbeing': 'Bienestar',
    'progress_area_creative':  'Creatividad',
    'progress_area_science':   'Ciencias',
    'snapshot_stars_label':   'Estrellas',
    'snapshot_correct_label': 'Correcto',
    'snapshot_streak_label':  'Racha de días',
    'snapshot_help_maths':   '¡Intenten contar objetos juntos en casa — los pequeños pasos construyen gran confianza!',
    'snapshot_help_english': 'Leer en voz alta juntos durante solo 10 minutos al día marca una gran diferencia.',
    'snapshot_help_science': '¡Las preguntas de ciencias cobran vida cuando exploráis experimentos sencillos en casa!',
    'snapshot_help_general': 'Explorar el mundo a través de libros, mapas o documentales impulsa el conocimiento general rápidamente.',
    'snapshot_weakest_suffix': 'tiene la menor cantidad de respuestas correctas.',
    'ai_chip_1': '¿Cómo apoyo a los lectores con NEE?',
    'ai_chip_2': '¿Qué temas de matemáticas son más difíciles?',
    'ai_chip_3': 'Recomienda una actividad para la edad de 5 años',
    'tier_activities_month': '{n} actividades este mes',
    'tier_next_label':       'Siguiente:',
    'quiz_modal_progress':   'Pregunta {n} de {total}',
    'quiz_modal_wrong':      'La respuesta es: {answer}',
    'quiz_modal_earned':     '¡Has ganado {reward}!',
    'article_modal_next':    'Siguiente',
    'article_modal_finish':  'Terminar',
    'confirm_self_label':    'Confirmo que he completado esta actividad',
    'confirm_joint_label':   'Confirmo que ambos completamos: {title}',
    'confirm_child_label':   'Mi hijo/a ha completado su parte',
    'reward_pill_both':      'Hijo/a gana {n} estrellas · Tú ganas: {reward}',
    'claim_reward_close':    'Reclamar recompensa y cerrar',
    'steps_confirm':         'Ambos completamos este paseo juntos',
    'checklist_found':       '{n} de {total} encontrados',
    'guided_step_label':     'Paso {n} de {total}',
    'guided_confirm':        'Completamos esta sesión de mindfulness juntos',
    'text_label_drawing':    'Describe el dibujo de tu hijo/a y añade un título:',
    'text_label_kind':       'Describe el acto amable que realizó tu hijo/a:',
    'text_confirm':          'Ambos confirmamos que esto fue completado',
    'story_confirm':         'Creamos esta historia juntos',
    'story_preview_intro':   'Tu historia: Érase una vez,',
    'rating_topic_label':    'Tu hijo/a eligió enseñarte sobre:',
    'rating_confirm':        'Mi hijo/a me enseñó sobre este tema hoy',
    'phrases_count':         '{n} de {total} practicados',
    'phrases_say_it':        'Dilo:',
    'phrases_confirm':       'Ambos practicamos estas frases juntos',
    'mystery_next_clue':     'Siguiente pista →',
    'mystery_confirm':       'Resolvimos este misterio juntos',
    'wallet_active_count':   '{n} activo(s)',
    'wallet_expires_day':    'Caduca en {n} día',
    'wallet_expires_days':   'Caduca en {n} días',
    'cap_solo_label':        'Actividades solo: {n}% del límite de 30% usado',
    'cap_combined_label':    'Combinado (A+B): {n}% del límite de 40% usado',
    'joint_parent_label':    'Padre/Madre',
    'joint_child_label':     'Hijo/a',
    'parent_act_supporting': 'apoyando a {name}',
    'module_desc_a':         'Completa estas actividades solo para apoyar mejor a tu hijo/a — y gana descuentos.',
    'module_desc_b':         'Haz estas actividades juntos con {name}. Ambos deben confirmar para desbloquear recompensas.',
    'module_desc_c':         'Ayuda a tu hijo/a a desarrollar hábitos del mundo real. Marca la casilla para confirmar.',
    'module_desc_d':         'Actividades extendidas en Bienestar, Creatividad, Valores y Cultura.',
  },
  'pl': {
    'progress_area_reading':   'Czytanie',
    'progress_area_numeracy':  'Numeracja',
    'progress_area_writing':   'Pisanie',
    'progress_area_wellbeing': 'Dobrostan',
    'progress_area_creative':  'Kreatywność',
    'progress_area_science':   'Nauka',
    'snapshot_stars_label':   'Gwiazdki',
    'snapshot_correct_label': 'Poprawne',
    'snapshot_streak_label':  'Seria dni',
    'snapshot_help_maths':   'Spróbujcie razem liczyć przedmioty w domu — małe kroki budują wielką pewność siebie!',
    'snapshot_help_english': 'Czytanie na głos razem przez zaledwie 10 minut dziennie robi ogromną różnicę.',
    'snapshot_help_science': 'Pytania naukowe ożywają, gdy odkrywacie proste eksperymenty w domu!',
    'snapshot_help_general': 'Poznawanie świata przez książki, mapy lub dokumenty szybko poszerza wiedzę ogólną.',
    'snapshot_weakest_suffix': 'ma najmniej poprawnych odpowiedzi.',
    'ai_chip_1': 'Jak wspierać czytelników z SPE?',
    'ai_chip_2': 'Które tematy matematyki są najtrudniejsze?',
    'ai_chip_3': 'Zaproponuj aktywność dla dziecka w wieku 5 lat',
    'tier_activities_month': '{n} aktywności w tym miesiącu',
    'tier_next_label':       'Następny:',
    'quiz_modal_progress':   'Pytanie {n} z {total}',
    'quiz_modal_wrong':      'Odpowiedź to: {answer}',
    'quiz_modal_earned':     'Zdobyłeś {reward}!',
    'article_modal_next':    'Następny',
    'article_modal_finish':  'Zakończ',
    'confirm_self_label':    'Potwierdzam, że ukończyłem tę aktywność',
    'confirm_joint_label':   'Potwierdzam, że oboje ukończyliśmy: {title}',
    'confirm_child_label':   'Moje dziecko ukończyło swoją część',
    'reward_pill_both':      'Dziecko zdobywa {n} gwiazdek · Ty zdobywasz: {reward}',
    'claim_reward_close':    'Odbierz nagrodę i zamknij',
    'steps_confirm':         'Oboje ukończyliśmy ten spacer razem',
    'checklist_found':       '{n} z {total} znalezionych',
    'guided_step_label':     'Krok {n} z {total}',
    'guided_confirm':        'Ukończyliśmy razem tę sesję uważności',
    'text_label_drawing':    'Opisz rysunek swojego dziecka i dodaj podpis:',
    'text_label_kind':       'Opisz życzliwy czyn, który wykonało twoje dziecko:',
    'text_confirm':          'Oboje potwierdzamy, że to zostało ukończone',
    'story_confirm':         'Razem stworzyliśmy tę historię',
    'story_preview_intro':   'Twoja historia: Dawno dawno temu,',
    'rating_topic_label':    'Twoje dziecko wybrało, żeby cię uczyć o:',
    'rating_confirm':        'Moje dziecko uczyło mnie o tym temacie dzisiaj',
    'phrases_count':         '{n} z {total} przećwiczonych',
    'phrases_say_it':        'Powiedz to:',
    'phrases_confirm':       'Oboje ćwiczyliśmy razem te zwroty',
    'mystery_next_clue':     'Następna wskazówka →',
    'mystery_confirm':       'Razem rozwiązaliśmy tę zagadkę',
    'wallet_active_count':   '{n} aktywny(ch)',
    'wallet_expires_day':    'Wygasa za {n} dzień',
    'wallet_expires_days':   'Wygasa za {n} dni',
    'cap_solo_label':        'Aktywności solo: {n}% z limitu 30% wykorzystane',
    'cap_combined_label':    'Łącznie (A+B): {n}% z limitu 40% wykorzystane',
    'joint_parent_label':    'Rodzic',
    'joint_child_label':     'Dziecko',
    'parent_act_supporting': 'wspieranie {name}',
    'module_desc_a':         'Ukończ te samodzielne aktywności, aby lepiej wspierać swoje dziecko — i zdobywaj rabaty.',
    'module_desc_b':         'Wykonuj te aktywności razem z {name}. Oboje muszą potwierdzić, aby odblokować nagrody.',
    'module_desc_c':         'Pomóż swojemu dziecku budować prawdziwe nawyki. Zaznacz pole, aby potwierdzić.',
    'module_desc_d':         'Rozszerzone aktywności z Dobrostanu, Kreatywności, Wartości i Kultury.',
  },
  'ur': {
    'progress_area_reading':   'پڑھنا',
    'progress_area_numeracy':  'حساب',
    'progress_area_writing':   'لکھنا',
    'progress_area_wellbeing': 'تندرستی',
    'progress_area_creative':  'تخلیقی',
    'progress_area_science':   'سائنس',
    'snapshot_stars_label':   'ستارے',
    'snapshot_correct_label': 'درست',
    'snapshot_streak_label':  'دن کا سلسلہ',
    'snapshot_help_maths':   'گھر میں چیزیں گنیں — چھوٹے قدم بڑا اعتماد بناتے ہیں!',
    'snapshot_help_english': 'روزانہ صرف 10 منٹ اونچی آواز میں پڑھنا بہت فرق کرتا ہے۔',
    'snapshot_help_science': 'گھر میں سادہ تجربات کریں — سائنسی سوالات زندہ ہو جاتے ہیں!',
    'snapshot_help_general': 'کتابوں، نقشوں یا دستاویزی فلموں سے دنیا کو جاننا عام علم کو تیزی سے بڑھاتا ہے۔',
    'snapshot_weakest_suffix': 'میں سب سے کم درست جوابات ہیں۔',
    'ai_chip_1': 'خصوصی ضروریات والے قارئین کی مدد کیسے کریں؟',
    'ai_chip_2': 'KS2 ریاضی کے کون سے موضوعات مشکل ترین ہیں؟',
    'ai_chip_3': '5 سال کی عمر کے لیے سرگرمی تجویز کریں',
    'tier_activities_month': 'اس ماہ {n} سرگرمیاں',
    'tier_next_label':       'اگلا:',
    'quiz_modal_progress':   'سوال {n} از {total}',
    'quiz_modal_wrong':      'جواب ہے: {answer}',
    'quiz_modal_earned':     'آپ نے {reward} حاصل کیا!',
    'article_modal_next':    'اگلا',
    'article_modal_finish':  'ختم کریں',
    'confirm_self_label':    'میں تصدیق کرتا/کرتی ہوں کہ میں نے یہ سرگرمی مکمل کی',
    'confirm_joint_label':   'میں تصدیق کرتا/کرتی ہوں کہ ہم دونوں نے مکمل کیا: {title}',
    'confirm_child_label':   'میرے بچے نے اپنا حصہ مکمل کیا',
    'reward_pill_both':      'بچہ {n} ستارے کماتا ہے · آپ کماتے ہیں: {reward}',
    'claim_reward_close':    'انعام حاصل کریں اور بند کریں',
    'steps_confirm':         'ہم دونوں نے یہ سیر مل کر مکمل کی',
    'checklist_found':       '{total} میں سے {n} ملے',
    'guided_step_label':     'قدم {n} از {total}',
    'guided_confirm':        'ہم نے یہ ذہن سازی مل کر مکمل کی',
    'text_label_drawing':    'اپنے بچے کی ڈرائنگ کی وضاحت کریں:',
    'text_label_kind':       'اپنے بچے کے مہربان عمل کی وضاحت کریں:',
    'text_confirm':          'ہم دونوں تصدیق کرتے ہیں کہ یہ مکمل ہوا',
    'story_confirm':         'ہم نے یہ کہانی مل کر بنائی',
    'story_preview_intro':   'آپ کی کہانی: ایک بار کی بات ہے،',
    'rating_topic_label':    'آپ کے بچے نے آپ کو یہ سکھانا چنا:',
    'rating_confirm':        'میرے بچے نے آج مجھے یہ موضوع سکھایا',
    'phrases_count':         '{total} میں سے {n} مشق کیے',
    'phrases_say_it':        'بولیں:',
    'phrases_confirm':       'ہم دونوں نے یہ جملے مل کر مشق کیے',
    'mystery_next_clue':     'اگلا سراغ →',
    'mystery_confirm':       'ہم نے یہ راز مل کر حل کیا',
    'wallet_active_count':   '{n} فعال',
    'wallet_expires_day':    '{n} دن میں ختم',
    'wallet_expires_days':   '{n} دنوں میں ختم',
    'cap_solo_label':        'انفرادی سرگرمیاں: 30% کی حد سے {n}% استعمال',
    'cap_combined_label':    'مجموعی (A+B): 40% کی حد سے {n}% استعمال',
    'joint_parent_label':    'والدین',
    'joint_child_label':     'بچہ',
    'parent_act_supporting': '{name} کی مدد',
    'module_desc_a':         'اپنے بچے کو بہتر سہارا دینے کے لیے یہ انفرادی سرگرمیاں مکمل کریں۔',
    'module_desc_b':         '{name} کے ساتھ مل کر یہ سرگرمیاں کریں۔ انعامات کے لیے دونوں کو تصدیق کرنی ہوگی۔',
    'module_desc_c':         'اپنے بچے کو حقیقی عادتیں بنانے میں مدد کریں۔ تصدیق کے لیے چیک باکس پر نشان لگائیں۔',
    'module_desc_d':         'فلاح، تخلیقیت، اقدار اور ثقافت میں توسیعی سرگرمیاں۔',
  },
  'bn': {
    'progress_area_reading':   'পড়া',
    'progress_area_numeracy':  'গণিত',
    'progress_area_writing':   'লেখা',
    'progress_area_wellbeing': 'সুস্থতা',
    'progress_area_creative':  'সৃজনশীলতা',
    'progress_area_science':   'বিজ্ঞান',
    'snapshot_stars_label':   'তারা',
    'snapshot_correct_label': 'সঠিক',
    'snapshot_streak_label':  'দিনের ধারা',
    'snapshot_help_maths':   'বাড়িতে একসাথে জিনিস গণনা করার চেষ্টা করুন — ছোট পদক্ষেপ বড় আত্মবিশ্বাস তৈরি করে!',
    'snapshot_help_english': 'প্রতিদিন মাত্র ১০ মিনিট একসাথে জোরে পড়া অনেক পার্থক্য করে।',
    'snapshot_help_science': 'ঘরে সহজ পরীক্ষা-নিরীক্ষা করলে বিজ্ঞানের প্রশ্নগুলো জীবন্ত হয়ে ওঠে!',
    'snapshot_help_general': 'বই, মানচিত্র বা তথ্যচিত্রের মাধ্যমে বিশ্ব অন্বেষণ সাধারণ জ্ঞান দ্রুত বাড়ায়।',
    'snapshot_weakest_suffix': 'এর সবচেয়ে কম সঠিক উত্তর আছে।',
    'ai_chip_1': 'আমি কীভাবে বিশেষ প্রয়োজনের পাঠকদের সহায়তা করব?',
    'ai_chip_2': 'কোন গণিত বিষয়গুলো সবচেয়ে কঠিন?',
    'ai_chip_3': '৫ বছর বয়সের জন্য একটি কার্যক্রম সুপারিশ করুন',
    'tier_activities_month': 'এই মাসে {n}টি কার্যক্রম',
    'tier_next_label':       'পরবর্তী:',
    'quiz_modal_progress':   '{total}টির মধ্যে {n}নং প্রশ্ন',
    'quiz_modal_wrong':      'উত্তর হলো: {answer}',
    'quiz_modal_earned':     'আপনি {reward} অর্জন করেছেন!',
    'article_modal_next':    'পরবর্তী',
    'article_modal_finish':  'শেষ করুন',
    'confirm_self_label':    'আমি নিশ্চিত করছি যে আমি এই কার্যক্রম সম্পন্ন করেছি',
    'confirm_joint_label':   'আমি নিশ্চিত করছি যে আমরা দুজনেই সম্পন্ন করেছি: {title}',
    'confirm_child_label':   'আমার সন্তান তার অংশ সম্পন্ন করেছে',
    'reward_pill_both':      'সন্তান {n} তারা অর্জন করে · আপনি অর্জন করেন: {reward}',
    'claim_reward_close':    'পুরস্কার নিন এবং বন্ধ করুন',
    'steps_confirm':         'আমরা দুজনে একসাথে এই হাঁটা সম্পন্ন করেছি',
    'checklist_found':       '{total}টির মধ্যে {n}টি পাওয়া গেছে',
    'guided_step_label':     '{total}টির মধ্যে {n}নং ধাপ',
    'guided_confirm':        'আমরা একসাথে এই মাইন্ডফুলনেস সেশন সম্পন্ন করেছি',
    'text_label_drawing':    'আপনার সন্তানের আঁকা বর্ণনা করুন এবং একটি ক্যাপশন যোগ করুন:',
    'text_label_kind':       'আপনার সন্তানের সদয় কাজটি বর্ণনা করুন:',
    'text_confirm':          'আমরা দুজনেই নিশ্চিত করছি যে এটি সম্পন্ন হয়েছে',
    'story_confirm':         'আমরা একসাথে এই গল্প তৈরি করেছি',
    'story_preview_intro':   'আপনার গল্প: একদা,',
    'rating_topic_label':    'আপনার সন্তান আপনাকে এই বিষয়ে শেখাতে বেছে নিয়েছে:',
    'rating_confirm':        'আমার সন্তান আজ আমাকে এই বিষয়ে শিখিয়েছে',
    'phrases_count':         '{total}টির মধ্যে {n}টি অনুশীলন করা হয়েছে',
    'phrases_say_it':        'বলুন:',
    'phrases_confirm':       'আমরা দুজনে একসাথে এই বাক্যাংশগুলো অনুশীলন করেছি',
    'mystery_next_clue':     'পরবর্তী সূত্র →',
    'mystery_confirm':       'আমরা একসাথে এই রহস্য সমাধান করেছি',
    'wallet_active_count':   '{n}টি সক্রিয়',
    'wallet_expires_day':    '{n} দিনে মেয়াদ শেষ',
    'wallet_expires_days':   '{n} দিনে মেয়াদ শেষ',
    'cap_solo_label':        'একক কার্যক্রম: ৩০% সীমার {n}% ব্যবহৃত',
    'cap_combined_label':    'মিলিত (A+B): ৪০% সীমার {n}% ব্যবহৃত',
    'joint_parent_label':    'অভিভাবক',
    'joint_child_label':     'শিশু',
    'parent_act_supporting': '{name} কে সহায়তা',
    'module_desc_a':         'আপনার সন্তানকে আরও ভালোভাবে সহায়তা করতে এই একক কার্যক্রমগুলো সম্পন্ন করুন।',
    'module_desc_b':         '{name} এর সাথে একসাথে এই কার্যক্রমগুলো করুন। পুরস্কার পেতে উভয়কেই নিশ্চিত করতে হবে।',
    'module_desc_c':         'আপনার সন্তানকে বাস্তব জীবনের অভ্যাস গড়তে সাহায্য করুন।',
    'module_desc_d':         'সুস্থতা, সৃজনশীলতা, মূল্যবোধ এবং সংস্কৃতিতে বিস্তারিত কার্যক্রম।',
  },
  'pa': {
    'progress_area_reading':   'ਪੜ੍ਹਨਾ',
    'progress_area_numeracy':  'ਸੰਖਿਆ ਗਿਆਨ',
    'progress_area_writing':   'ਲਿਖਣਾ',
    'progress_area_wellbeing': 'ਭਲਾਈ',
    'progress_area_creative':  'ਸਿਰਜਣਾਤਮਕ',
    'progress_area_science':   'ਵਿਗਿਆਨ',
    'snapshot_stars_label':   'ਤਾਰੇ',
    'snapshot_correct_label': 'ਸਹੀ',
    'snapshot_streak_label':  'ਦਿਨਾਂ ਦੀ ਲੜੀ',
    'snapshot_help_maths':   'ਘਰ ਵਿੱਚ ਮਿਲ ਕੇ ਚੀਜ਼ਾਂ ਗਿਣਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ — ਛੋਟੇ ਕਦਮ ਵੱਡਾ ਭਰੋਸਾ ਬਣਾਉਂਦੇ ਹਨ!',
    'snapshot_help_english': 'ਰੋਜ਼ਾਨਾ ਸਿਰਫ਼ 10 ਮਿੰਟ ਉੱਚੀ ਆਵਾਜ਼ ਵਿੱਚ ਪੜ੍ਹਨਾ ਬਹੁਤ ਵੱਡਾ ਫ਼ਰਕ ਪਾਉਂਦਾ ਹੈ।',
    'snapshot_help_science': 'ਘਰ ਵਿੱਚ ਸਧਾਰਨ ਪ੍ਰਯੋਗ ਕਰਨ ਨਾਲ ਵਿਗਿਆਨ ਦੇ ਸਵਾਲ ਜ਼ਿੰਦਾ ਹੋ ਜਾਂਦੇ ਹਨ!',
    'snapshot_help_general': 'ਕਿਤਾਬਾਂ, ਨਕਸ਼ਿਆਂ ਜਾਂ ਦਸਤਾਵੇਜ਼ੀ ਫ਼ਿਲਮਾਂ ਰਾਹੀਂ ਦੁਨੀਆ ਜਾਣਨ ਨਾਲ ਆਮ ਗਿਆਨ ਜਲਦੀ ਵਧਦਾ ਹੈ।',
    'snapshot_weakest_suffix': 'ਵਿੱਚ ਸਭ ਤੋਂ ਘੱਟ ਸਹੀ ਜਵਾਬ ਹਨ।',
    'ai_chip_1': 'ਮੈਂ ਵਿਸ਼ੇਸ਼ ਲੋੜਾਂ ਵਾਲੇ ਪਾਠਕਾਂ ਦੀ ਮਦਦ ਕਿਵੇਂ ਕਰਾਂ?',
    'ai_chip_2': 'KS2 ਗਣਿਤ ਦੇ ਕਿਹੜੇ ਵਿਸ਼ੇ ਸਭ ਤੋਂ ਔਖੇ ਹਨ?',
    'ai_chip_3': '5 ਸਾਲ ਦੀ ਉਮਰ ਲਈ ਗਤੀਵਿਧੀ ਸੁਝਾਓ',
    'tier_activities_month': 'ਇਸ ਮਹੀਨੇ {n} ਗਤੀਵਿਧੀਆਂ',
    'tier_next_label':       'ਅਗਲਾ:',
    'quiz_modal_progress':   '{total} ਵਿੱਚੋਂ {n}ਵਾਂ ਸਵਾਲ',
    'quiz_modal_wrong':      'ਜਵਾਬ ਹੈ: {answer}',
    'quiz_modal_earned':     'ਤੁਸੀਂ {reward} ਕਮਾਏ!',
    'article_modal_next':    'ਅਗਲਾ',
    'article_modal_finish':  'ਮੁਕੰਮਲ ਕਰੋ',
    'confirm_self_label':    'ਮੈਂ ਪੁਸ਼ਟੀ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ ਕਿ ਮੈਂ ਇਹ ਗਤੀਵਿਧੀ ਪੂਰੀ ਕੀਤੀ',
    'confirm_joint_label':   'ਮੈਂ ਪੁਸ਼ਟੀ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ ਕਿ ਅਸੀਂ ਦੋਵੇਂ ਮੁਕੰਮਲ ਕੀਤਾ: {title}',
    'confirm_child_label':   'ਮੇਰੇ ਬੱਚੇ ਨੇ ਆਪਣਾ ਹਿੱਸਾ ਪੂਰਾ ਕੀਤਾ',
    'reward_pill_both':      'ਬੱਚਾ {n} ਤਾਰੇ ਕਮਾਉਂਦਾ ਹੈ · ਤੁਸੀਂ ਕਮਾਉਂਦੇ ਹੋ: {reward}',
    'claim_reward_close':    'ਇਨਾਮ ਲਓ ਅਤੇ ਬੰਦ ਕਰੋ',
    'steps_confirm':         'ਅਸੀਂ ਦੋਵੇਂ ਇਹ ਸੈਰ ਮਿਲ ਕੇ ਮੁਕੰਮਲ ਕੀਤੀ',
    'checklist_found':       '{total} ਵਿੱਚੋਂ {n} ਮਿਲੇ',
    'guided_step_label':     '{total} ਵਿੱਚੋਂ {n}ਵਾਂ ਕਦਮ',
    'guided_confirm':        'ਅਸੀਂ ਮਿਲ ਕੇ ਇਹ ਮਾਈਂਡਫੁੱਲਨੈੱਸ ਸੈਸ਼ਨ ਮੁਕੰਮਲ ਕੀਤਾ',
    'text_label_drawing':    'ਆਪਣੇ ਬੱਚੇ ਦੀ ਡਰਾਇੰਗ ਦੱਸੋ ਅਤੇ ਸਿਰਲੇਖ ਲਿਖੋ:',
    'text_label_kind':       'ਆਪਣੇ ਬੱਚੇ ਦੇ ਦਿਆਲੂ ਕੰਮ ਦੱਸੋ:',
    'text_confirm':          'ਅਸੀਂ ਦੋਵੇਂ ਪੁਸ਼ਟੀ ਕਰਦੇ ਹਾਂ ਕਿ ਇਹ ਮੁਕੰਮਲ ਹੋਇਆ',
    'story_confirm':         'ਅਸੀਂ ਮਿਲ ਕੇ ਇਹ ਕਹਾਣੀ ਬਣਾਈ',
    'story_preview_intro':   'ਤੁਹਾਡੀ ਕਹਾਣੀ: ਇੱਕ ਵਾਰ ਦੀ ਗੱਲ,',
    'rating_topic_label':    'ਤੁਹਾਡੇ ਬੱਚੇ ਨੇ ਤੁਹਾਨੂੰ ਇਸ ਬਾਰੇ ਸਿਖਾਉਣ ਦੀ ਚੋਣ ਕੀਤੀ:',
    'rating_confirm':        'ਮੇਰੇ ਬੱਚੇ ਨੇ ਅੱਜ ਮੈਨੂੰ ਇਹ ਵਿਸ਼ਾ ਸਿਖਾਇਆ',
    'phrases_count':         '{total} ਵਿੱਚੋਂ {n} ਅਭਿਆਸ ਕੀਤੇ',
    'phrases_say_it':        'ਬੋਲੋ:',
    'phrases_confirm':       'ਅਸੀਂ ਦੋਵੇਂ ਮਿਲ ਕੇ ਇਹ ਵਾਕਾਂਸ਼ ਅਭਿਆਸ ਕੀਤੇ',
    'mystery_next_clue':     'ਅਗਲਾ ਸੁਰਾਗ →',
    'mystery_confirm':       'ਅਸੀਂ ਮਿਲ ਕੇ ਇਹ ਰਹੱਸ ਹੱਲ ਕੀਤਾ',
    'wallet_active_count':   '{n} ਸਰਗਰਮ',
    'wallet_expires_day':    '{n} ਦਿਨ ਵਿੱਚ ਮਿਆਦ ਖਤਮ',
    'wallet_expires_days':   '{n} ਦਿਨਾਂ ਵਿੱਚ ਮਿਆਦ ਖਤਮ',
    'cap_solo_label':        'ਇਕੱਲੀਆਂ ਗਤੀਵਿਧੀਆਂ: 30% ਸੀਮਾ ਦਾ {n}% ਵਰਤਿਆ',
    'cap_combined_label':    'ਮਿਲਿਆ (A+B): 40% ਸੀਮਾ ਦਾ {n}% ਵਰਤਿਆ',
    'joint_parent_label':    'ਮਾਪੇ',
    'joint_child_label':     'ਬੱਚਾ',
    'parent_act_supporting': '{name} ਦੀ ਮਦਦ',
    'module_desc_a':         'ਆਪਣੇ ਬੱਚੇ ਨੂੰ ਬਿਹਤਰ ਸਹਾਰਾ ਦੇਣ ਲਈ ਇਹ ਇਕੱਲੀਆਂ ਗਤੀਵਿਧੀਆਂ ਮੁਕੰਮਲ ਕਰੋ।',
    'module_desc_b':         '{name} ਨਾਲ ਮਿਲ ਕੇ ਇਹ ਗਤੀਵਿਧੀਆਂ ਕਰੋ। ਇਨਾਮਾਂ ਲਈ ਦੋਵਾਂ ਨੂੰ ਪੁਸ਼ਟੀ ਕਰਨੀ ਪਵੇਗੀ।',
    'module_desc_c':         'ਆਪਣੇ ਬੱਚੇ ਨੂੰ ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੀਆਂ ਆਦਤਾਂ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰੋ।',
    'module_desc_d':         'ਭਲਾਈ, ਸਿਰਜਣਾਤਮਕਤਾ, ਕਦਰਾਂ ਅਤੇ ਸੱਭਿਆਚਾਰ ਵਿੱਚ ਵਿਸਤ੍ਰਿਤ ਗਤੀਵਿਧੀਆਂ।',
  },
  'gu': {
    'progress_area_reading':   'વાંચન',
    'progress_area_numeracy':  'અંકગણિત',
    'progress_area_writing':   'લેખન',
    'progress_area_wellbeing': 'સ્વાસ્થ્ય',
    'progress_area_creative':  'સર્જનાત્મક',
    'progress_area_science':   'વિજ્ઞાન',
    'snapshot_stars_label':   'તારા',
    'snapshot_correct_label': 'સાચું',
    'snapshot_streak_label':  'દિવસની હારમાળા',
    'snapshot_help_maths':   'ઘરે સાથે મળીને વસ્તુઓ ગણો — નાના પગલાં મોટો આત્મવિશ્વાસ બનાવે છે!',
    'snapshot_help_english': 'દરરોજ માત્ર 10 મિનિટ ઊંચા અવાજે સાથે વાંચવું ઘણો ફરક પાડે છે.',
    'snapshot_help_science': 'ઘરે સરળ પ્રયોગો કરો — વિજ્ઞાનના પ્રશ્નો જીવંત થઈ જાય છે!',
    'snapshot_help_general': 'પુસ્તકો, નકશા અથવા દસ્તાવેજી ફિલ્મો દ્વારા વિશ્વ જાણવું સામાન્ય જ્ઞાન ઝડપથી વધારે છે.',
    'snapshot_weakest_suffix': 'માં સૌથી ઓછા સાચા જવાબ છે.',
    'ai_chip_1': 'હું વિશેષ જરૂરિયાત ધરાવતા વાચકોને કેવી રીતે ટેકો આપું?',
    'ai_chip_2': 'KS2 ગણિતના કયા વિષયો સૌથી કઠિન છે?',
    'ai_chip_3': '5 વર્ષની ઉંમર માટે પ્રવૃત્તિ સૂચવો',
    'tier_activities_month': 'આ મહિને {n} પ્રવૃત્તિઓ',
    'tier_next_label':       'આગળ:',
    'quiz_modal_progress':   '{total} માંથી પ્રશ્ન {n}',
    'quiz_modal_wrong':      'જવાબ છે: {answer}',
    'quiz_modal_earned':     'તમે {reward} કમાયા!',
    'article_modal_next':    'આગળ',
    'article_modal_finish':  'સમાપ્ત',
    'confirm_self_label':    'હું પુષ્ટિ કરું છું કે મેં આ પ્રવૃત્તિ પૂર્ણ કરી',
    'confirm_joint_label':   'હું પુષ્ટિ કરું છું કે અમે બંનેએ પૂર્ણ કર્યું: {title}',
    'confirm_child_label':   'મારા બાળકે તેનો ભાગ પૂર્ણ કર્યો',
    'reward_pill_both':      'બાળક {n} તારા કમાય છે · તમે કમાઓ: {reward}',
    'claim_reward_close':    'ઇનામ મેળવો અને બંધ કરો',
    'steps_confirm':         'અમે બંને આ ચાલ સાથે મળીને પૂર્ણ કરી',
    'checklist_found':       '{total} માંથી {n} મળ્યા',
    'guided_step_label':     '{total} માંથી પગલું {n}',
    'guided_confirm':        'અમે સાથે મળીને આ માઇન્ડફુલનેસ સેશન પૂર્ણ કર્યું',
    'text_label_drawing':    'તમારા બાળકના ચિત્રનું વર્ણન કરો અને મથાળું ઉમેરો:',
    'text_label_kind':       'તમારા બાળકે કરેલ દયાળુ કાર્ય વર્ણવો:',
    'text_confirm':          'અમે બંને પુષ્ટિ કરીએ છીએ કે આ પૂર્ણ થયું',
    'story_confirm':         'અમે સાથે મળીને આ વાર્તા બનાવી',
    'story_preview_intro':   'તમારી વાર્તા: એક સમયે,',
    'rating_topic_label':    'તમારા બાળકે તમને આ વિશે શીખવવાનું પસંદ કર્યું:',
    'rating_confirm':        'આજે મારા બાળકે મને આ વિષય શીખવ્યો',
    'phrases_count':         '{total} માંથી {n} અભ્યાસ કર્યા',
    'phrases_say_it':        'બોલો:',
    'phrases_confirm':       'અમે બંને સાથે આ શબ્દસમૂહો અભ્યાસ કર્યા',
    'mystery_next_clue':     'આગળનો સંકેત →',
    'mystery_confirm':       'અમે સાથે આ રહસ્ય ઉકેલ્યું',
    'wallet_active_count':   '{n} સક્રિય',
    'wallet_expires_day':    '{n} દિવસમાં સમાપ્ત',
    'wallet_expires_days':   '{n} દિવસોમાં સમાપ્ત',
    'cap_solo_label':        'એકલ પ્રવૃત્તિઓ: 30% મર્યાદામાંથી {n}% વપરાઈ',
    'cap_combined_label':    'સંયુક્ત (A+B): 40% મર્યાદામાંથી {n}% વપરાઈ',
    'joint_parent_label':    'માતા-પિતા',
    'joint_child_label':     'બાળક',
    'parent_act_supporting': '{name}ને ટેકો',
    'module_desc_a':         'તમારા બાળકને વધુ સારી રીતે ટેકો આપવા આ એકલ પ્રવૃત્તિઓ પૂર્ણ કરો.',
    'module_desc_b':         '{name} સાથે આ પ્રવૃત્તિઓ કરો. ઇનામ માટે બંનેએ પુષ્ટિ કરવી આવશ્યક.',
    'module_desc_c':         'તમારા બાળકને વાસ્તવિક જીવનની આદતો બનાવવામાં મદદ કરો.',
    'module_desc_d':         'સ્વાસ્થ્ય, સર્જનાત્મકતા, મૂલ્યો અને સંસ્કૃતિમાં વિસ્તૃત પ્રવૃત્તિઓ.',
  },
  'hi': {
    'progress_area_reading':   'पढ़ना',
    'progress_area_numeracy':  'गणित',
    'progress_area_writing':   'लिखना',
    'progress_area_wellbeing': 'भलाई',
    'progress_area_creative':  'रचनात्मक',
    'progress_area_science':   'विज्ञान',
    'snapshot_stars_label':   'तारे',
    'snapshot_correct_label': 'सही',
    'snapshot_streak_label':  'दिनों की श्रृंखला',
    'snapshot_help_maths':   'घर पर मिलकर चीज़ें गिनने की कोशिश करें — छोटे कदम बड़ा आत्मविश्वास बनाते हैं!',
    'snapshot_help_english': 'रोज़ाना सिर्फ़ 10 मिनट मिलकर ज़ोर से पढ़ना बहुत बड़ा फ़र्क़ करता है।',
    'snapshot_help_science': 'घर पर सरल प्रयोग करें — विज्ञान के सवाल जीवंत हो जाते हैं!',
    'snapshot_help_general': 'किताबों, नक्शों या डॉक्यूमेंट्री से दुनिया जानना सामान्य ज्ञान तेज़ी से बढ़ाता है।',
    'snapshot_weakest_suffix': 'में सबसे कम सही उत्तर हैं।',
    'ai_chip_1': 'मैं विशेष ज़रूरत वाले पाठकों की मदद कैसे करूँ?',
    'ai_chip_2': 'KS2 गणित के कौन से विषय सबसे कठिन हैं?',
    'ai_chip_3': '5 साल की उम्र के लिए कोई गतिविधि सुझाएँ',
    'tier_activities_month': 'इस महीने {n} गतिविधियाँ',
    'tier_next_label':       'अगला:',
    'quiz_modal_progress':   'प्रश्न {n} / {total}',
    'quiz_modal_wrong':      'उत्तर है: {answer}',
    'quiz_modal_earned':     'आपने {reward} अर्जित किया!',
    'article_modal_next':    'अगला',
    'article_modal_finish':  'समाप्त',
    'confirm_self_label':    'मैं पुष्टि करता/करती हूँ कि मैंने यह गतिविधि पूरी की',
    'confirm_joint_label':   'मैं पुष्टि करता/करती हूँ कि हम दोनों ने पूरा किया: {title}',
    'confirm_child_label':   'मेरे बच्चे ने अपना हिस्सा पूरा कर लिया',
    'reward_pill_both':      'बच्चा {n} तारे कमाता है · आप कमाते हैं: {reward}',
    'claim_reward_close':    'पुरस्कार पाएँ और बंद करें',
    'steps_confirm':         'हम दोनों ने यह सैर मिलकर पूरी की',
    'checklist_found':       '{total} में से {n} मिले',
    'guided_step_label':     '{total} में से चरण {n}',
    'guided_confirm':        'हमने मिलकर यह माइंडफुलनेस सेशन पूरा किया',
    'text_label_drawing':    'अपने बच्चे की ड्राइंग का वर्णन करें और एक कैप्शन जोड़ें:',
    'text_label_kind':       'अपने बच्चे के दयालु कार्य का वर्णन करें:',
    'text_confirm':          'हम दोनों पुष्टि करते हैं कि यह पूरा हो गया',
    'story_confirm':         'हमने मिलकर यह कहानी बनाई',
    'story_preview_intro':   'आपकी कहानी: एक बार की बात,',
    'rating_topic_label':    'आपके बच्चे ने आपको यह सिखाना चुना:',
    'rating_confirm':        'मेरे बच्चे ने आज मुझे यह विषय सिखाया',
    'phrases_count':         '{total} में से {n} का अभ्यास किया',
    'phrases_say_it':        'बोलें:',
    'phrases_confirm':       'हम दोनों ने मिलकर इन वाक्यांशों का अभ्यास किया',
    'mystery_next_clue':     'अगला सुराग →',
    'mystery_confirm':       'हमने मिलकर यह रहस्य सुलझाया',
    'wallet_active_count':   '{n} सक्रिय',
    'wallet_expires_day':    '{n} दिन में समाप्त',
    'wallet_expires_days':   '{n} दिनों में समाप्त',
    'cap_solo_label':        'अकेली गतिविधियाँ: 30% सीमा का {n}% उपयोग',
    'cap_combined_label':    'संयुक्त (A+B): 40% सीमा का {n}% उपयोग',
    'joint_parent_label':    'माता-पिता',
    'joint_child_label':     'बच्चा',
    'parent_act_supporting': '{name} की मदद',
    'module_desc_a':         'अपने बच्चे को बेहतर सहारा देने के लिए ये अकेली गतिविधियाँ पूरी करें।',
    'module_desc_b':         '{name} के साथ मिलकर ये गतिविधियाँ करें। पुरस्कारों के लिए दोनों को पुष्टि करनी होगी।',
    'module_desc_c':         'अपने बच्चे को वास्तविक जीवन की आदतें बनाने में मदद करें।',
    'module_desc_d':         'भलाई, रचनात्मकता, मूल्यों और संस्कृति में विस्तारित गतिविधियाँ।',
  },
  'ar': {
    'progress_area_reading':   'القراءة',
    'progress_area_numeracy':  'الحساب',
    'progress_area_writing':   'الكتابة',
    'progress_area_wellbeing': 'الرفاهية',
    'progress_area_creative':  'الإبداع',
    'progress_area_science':   'العلوم',
    'snapshot_stars_label':   'نجوم',
    'snapshot_correct_label': 'صحيح',
    'snapshot_streak_label':  'أيام متتالية',
    'snapshot_help_maths':   'حاولوا معًا عدّ الأشياء في المنزل — الخطوات الصغيرة تبني ثقة كبيرة!',
    'snapshot_help_english': 'القراءة بصوت عالٍ معًا 10 دقائق فقط يوميًا تحدث فرقًا كبيرًا.',
    'snapshot_help_science': 'تصبح أسئلة العلوم حيّة عندما تستكشفون تجارب بسيطة في المنزل!',
    'snapshot_help_general': 'استكشاف العالم من خلال الكتب والخرائط والأفلام الوثائقية يعزز المعرفة العامة بسرعة.',
    'snapshot_weakest_suffix': 'لديها أقل عدد من الإجابات الصحيحة.',
    'ai_chip_1': 'كيف أدعم القرّاء ذوي الاحتياجات الخاصة؟',
    'ai_chip_2': 'ما أصعب موضوعات رياضيات KS2؟',
    'ai_chip_3': 'أقترح نشاطًا لعمر 5 سنوات',
    'tier_activities_month': '{n} أنشطة هذا الشهر',
    'tier_next_label':       'التالي:',
    'quiz_modal_progress':   'السؤال {n} من {total}',
    'quiz_modal_wrong':      'الإجابة هي: {answer}',
    'quiz_modal_earned':     'لقد حصلت على {reward}!',
    'article_modal_next':    'التالي',
    'article_modal_finish':  'إنهاء',
    'confirm_self_label':    'أؤكد أنني أتممت هذا النشاط',
    'confirm_joint_label':   'أؤكد أننا كلانا أتممنا: {title}',
    'confirm_child_label':   'أتمّ طفلي جزءه',
    'reward_pill_both':      'الطفل يكسب {n} نجوم · أنت تكسب: {reward}',
    'claim_reward_close':    'المطالبة بالمكافأة وإغلاق',
    'steps_confirm':         'أتممنا معًا هذه الجولة',
    'checklist_found':       '{n} من {total} وُجد',
    'guided_step_label':     'الخطوة {n} من {total}',
    'guided_confirm':        'أتممنا معًا جلسة اليقظة هذه',
    'text_label_drawing':    'صف رسم طفلك وأضف تعليقًا:',
    'text_label_kind':       'صف الفعل اللطيف الذي قام به طفلك:',
    'text_confirm':          'كلانا يؤكد أن هذا قد اكتمل',
    'story_confirm':         'أنشأنا هذه القصة معًا',
    'story_preview_intro':   'قصتك: كان يا ما كان،',
    'rating_topic_label':    'اختار طفلك أن يعلّمك عن:',
    'rating_confirm':        'علّمني طفلي هذا الموضوع اليوم',
    'phrases_count':         '{n} من {total} تمّ تدريبها',
    'phrases_say_it':        'قلها:',
    'phrases_confirm':       'تدرّبنا معًا على هذه العبارات',
    'mystery_next_clue':     'التلميح التالي →',
    'mystery_confirm':       'حللنا هذا اللغز معًا',
    'wallet_active_count':   '{n} نشط(ة)',
    'wallet_expires_day':    'تنتهي في {n} يوم',
    'wallet_expires_days':   'تنتهي في {n} أيام',
    'cap_solo_label':        'الأنشطة المنفردة: {n}% من حد 30% مستخدم',
    'cap_combined_label':    'المجموع (A+B): {n}% من حد 40% مستخدم',
    'joint_parent_label':    'الوالد/الوالدة',
    'joint_child_label':     'الطفل',
    'parent_act_supporting': 'دعم {name}',
    'module_desc_a':         'أكمل هذه الأنشطة المنفردة لدعم طفلك بشكل أفضل — واكسب خصومات.',
    'module_desc_b':         'اقم بهذه الأنشطة معًا مع {name}. يجب على الاثنين التأكيد لفتح المكافآت.',
    'module_desc_c':         'ساعد طفلك على بناء عادات الحياة الواقعية.',
    'module_desc_d':         'أنشطة ممتدة في الرفاهية والإبداع والقيم والثقافة.',
  },
  'pt': {
    'progress_area_reading':   'Leitura',
    'progress_area_numeracy':  'Numeracia',
    'progress_area_writing':   'Escrita',
    'progress_area_wellbeing': 'Bem-estar',
    'progress_area_creative':  'Criatividade',
    'progress_area_science':   'Ciências',
    'snapshot_stars_label':   'Estrelas',
    'snapshot_correct_label': 'Correto',
    'snapshot_streak_label':  'Dias seguidos',
    'snapshot_help_maths':   'Tentem contar objetos juntos em casa — pequenos passos constroem grande confiança!',
    'snapshot_help_english': 'Ler em voz alta juntos por apenas 10 minutos por dia faz uma enorme diferença.',
    'snapshot_help_science': 'As perguntas de ciências ganham vida quando exploram experiências simples em casa!',
    'snapshot_help_general': 'Explorar o mundo através de livros, mapas ou documentários impulsiona rapidamente o conhecimento geral.',
    'snapshot_weakest_suffix': 'tem menos respostas corretas.',
    'ai_chip_1': 'Como apoio leitores com NEE?',
    'ai_chip_2': 'Quais temas de matemática são mais difíceis?',
    'ai_chip_3': 'Recomende uma atividade para 5 anos',
    'tier_activities_month': '{n} atividades este mês',
    'tier_next_label':       'Próximo:',
    'quiz_modal_progress':   'Pergunta {n} de {total}',
    'quiz_modal_wrong':      'A resposta é: {answer}',
    'quiz_modal_earned':     'Ganhou {reward}!',
    'article_modal_next':    'Próximo',
    'article_modal_finish':  'Terminar',
    'confirm_self_label':    'Confirmo que completei esta atividade',
    'confirm_joint_label':   'Confirmo que ambos completámos: {title}',
    'confirm_child_label':   'O meu filho completou a sua parte',
    'reward_pill_both':      'Criança ganha {n} estrelas · Você ganha: {reward}',
    'claim_reward_close':    'Reivindicar recompensa e fechar',
    'steps_confirm':         'Ambos completámos este passeio juntos',
    'checklist_found':       '{n} de {total} encontrados',
    'guided_step_label':     'Passo {n} de {total}',
    'guided_confirm':        'Completámos juntos esta sessão de mindfulness',
    'text_label_drawing':    'Descreva o desenho do seu filho e adicione uma legenda:',
    'text_label_kind':       'Descreva o ato gentil realizado pelo seu filho:',
    'text_confirm':          'Ambos confirmamos que isto foi concluído',
    'story_confirm':         'Criámos esta história juntos',
    'story_preview_intro':   'A vossa história: Era uma vez,',
    'rating_topic_label':    'O seu filho escolheu ensinar-lhe sobre:',
    'rating_confirm':        'O meu filho ensinou-me sobre este tema hoje',
    'phrases_count':         '{n} de {total} praticados',
    'phrases_say_it':        'Diga:',
    'phrases_confirm':       'Ambos praticámos estas frases juntos',
    'mystery_next_clue':     'Próxima pista →',
    'mystery_confirm':       'Resolvemos este mistério juntos',
    'wallet_active_count':   '{n} ativo(s)',
    'wallet_expires_day':    'Expira em {n} dia',
    'wallet_expires_days':   'Expira em {n} dias',
    'cap_solo_label':        'Atividades solo: {n}% do limite de 30% usado',
    'cap_combined_label':    'Combinado (A+B): {n}% do limite de 40% usado',
    'joint_parent_label':    'Pai/Mãe',
    'joint_child_label':     'Criança',
    'parent_act_supporting': 'a apoiar {name}',
    'module_desc_a':         'Complete estas atividades solo para apoiar melhor o seu filho — e ganhe descontos.',
    'module_desc_b':         'Faça estas atividades juntos com {name}. Ambos devem confirmar para desbloquear recompensas.',
    'module_desc_c':         'Ajude o seu filho a desenvolver hábitos do mundo real.',
    'module_desc_d':         'Atividades alargadas em Bem-estar, Criatividade, Valores e Cultura.',
  },
  'ro': {
    'progress_area_reading':   'Lectură',
    'progress_area_numeracy':  'Numerație',
    'progress_area_writing':   'Scriere',
    'progress_area_wellbeing': 'Bunăstare',
    'progress_area_creative':  'Creativ',
    'progress_area_science':   'Știință',
    'snapshot_stars_label':   'Stele',
    'snapshot_correct_label': 'Corect',
    'snapshot_streak_label':  'Zile consecutive',
    'snapshot_help_maths':   'Încercați să numărați obiecte împreună acasă — pașii mici construiesc o mare încredere!',
    'snapshot_help_english': 'Cititul cu voce tare împreună timp de doar 10 minute pe zi face o diferență uriașă.',
    'snapshot_help_science': 'Întrebările de știință prind viață când explorați experimente simple acasă!',
    'snapshot_help_general': 'Explorarea lumii prin cărți, hărți sau documentare crește rapid cunoștințele generale.',
    'snapshot_weakest_suffix': 'are cele mai puține răspunsuri corecte.',
    'ai_chip_1': 'Cum sprijin cititorii cu nevoi speciale?',
    'ai_chip_2': 'Ce subiecte de matematică sunt cele mai dificile?',
    'ai_chip_3': 'Recomandați o activitate pentru vârsta de 5 ani',
    'tier_activities_month': '{n} activități în această lună',
    'tier_next_label':       'Următor:',
    'quiz_modal_progress':   'Întrebarea {n} din {total}',
    'quiz_modal_wrong':      'Răspunsul este: {answer}',
    'quiz_modal_earned':     'Ați câștigat {reward}!',
    'article_modal_next':    'Următor',
    'article_modal_finish':  'Termina',
    'confirm_self_label':    'Confirm că am finalizat această activitate',
    'confirm_joint_label':   'Confirm că am finalizat amândoi: {title}',
    'confirm_child_label':   'Copilul meu și-a finalizat partea',
    'reward_pill_both':      'Copil câștigă {n} stele · Tu câștigi: {reward}',
    'claim_reward_close':    'Revendicați recompensa și închideți',
    'steps_confirm':         'Amândoi am finalizat această plimbare împreună',
    'checklist_found':       '{n} din {total} găsite',
    'guided_step_label':     'Pasul {n} din {total}',
    'guided_confirm':        'Am finalizat împreună această sesiune de mindfulness',
    'text_label_drawing':    'Descrieți desenul copilului și adăugați o legendă:',
    'text_label_kind':       'Descrieți fapta bună a copilului:',
    'text_confirm':          'Amândoi confirmăm că a fost finalizat',
    'story_confirm':         'Am creat această poveste împreună',
    'story_preview_intro':   'Povestea voastră: A fost odată,',
    'rating_topic_label':    'Copilul dumneavoastră a ales să vă predea despre:',
    'rating_confirm':        'Copilul meu m-a învățat despre acest subiect astăzi',
    'phrases_count':         '{n} din {total} exersate',
    'phrases_say_it':        'Spuneți:',
    'phrases_confirm':       'Amândoi am exersat aceste fraze împreună',
    'mystery_next_clue':     'Indiciu următor →',
    'mystery_confirm':       'Am rezolvat împreună acest mister',
    'wallet_active_count':   '{n} activ(e)',
    'wallet_expires_day':    'Expiră în {n} zi',
    'wallet_expires_days':   'Expiră în {n} zile',
    'cap_solo_label':        'Activități solo: {n}% din limita de 30% folosit',
    'cap_combined_label':    'Combinat (A+B): {n}% din limita de 40% folosit',
    'joint_parent_label':    'Părinte',
    'joint_child_label':     'Copil',
    'parent_act_supporting': 'susținând {name}',
    'module_desc_a':         'Completați aceste activități solo pentru a susține mai bine copilul — și câștigați reduceri.',
    'module_desc_b':         'Faceți aceste activități împreună cu {name}. Amândoi trebuie să confirme pentru a debloca recompensele.',
    'module_desc_c':         'Ajutați copilul să dezvolte obiceiuri din viața reală.',
    'module_desc_d':         'Activități extinse în Bunăstare, Creativitate, Valori și Cultură.',
  },
  'zh': {
    'progress_area_reading':   '阅读',
    'progress_area_numeracy':  '数学能力',
    'progress_area_writing':   '写作',
    'progress_area_wellbeing': '健康',
    'progress_area_creative':  '创意',
    'progress_area_science':   '科学',
    'snapshot_stars_label':   '星星',
    'snapshot_correct_label': '正确',
    'snapshot_streak_label':  '连续天数',
    'snapshot_help_maths':   '试着在家一起数数——小步骤能建立大自信！',
    'snapshot_help_english': '每天只需一起大声朗读10分钟，就会产生很大的差异。',
    'snapshot_help_science': '在家做简单实验，科学问题就会活灵活现！',
    'snapshot_help_general': '通过书籍、地图或纪录片探索世界，能快速提升常识。',
    'snapshot_weakest_suffix': '的正确答案最少。',
    'ai_chip_1': '如何支持有特殊需求的阅读者？',
    'ai_chip_2': 'KS2数学哪些主题最难？',
    'ai_chip_3': '为5岁推荐一项活动',
    'tier_activities_month': '本月{n}个活动',
    'tier_next_label':       '下一级:',
    'quiz_modal_progress':   '第{n}题，共{total}题',
    'quiz_modal_wrong':      '答案是：{answer}',
    'quiz_modal_earned':     '您获得了{reward}！',
    'article_modal_next':    '下一步',
    'article_modal_finish':  '完成',
    'confirm_self_label':    '我确认已完成此活动',
    'confirm_joint_label':   '我确认我们两人都完成了：{title}',
    'confirm_child_label':   '我的孩子已完成其部分',
    'reward_pill_both':      '孩子获得{n}颗星 · 您获得：{reward}',
    'claim_reward_close':    '领取奖励并关闭',
    'steps_confirm':         '我们两人一起完成了这次散步',
    'checklist_found':       '{total}项中找到{n}项',
    'guided_step_label':     '第{n}步，共{total}步',
    'guided_confirm':        '我们一起完成了这次正念练习',
    'text_label_drawing':    '描述孩子的画作并添加说明：',
    'text_label_kind':       '描述孩子所做的善意行为：',
    'text_confirm':          '我们两人确认已完成',
    'story_confirm':         '我们一起创作了这个故事',
    'story_preview_intro':   '你们的故事：从前，',
    'rating_topic_label':    '您的孩子选择教您关于：',
    'rating_confirm':        '我的孩子今天教了我这个话题',
    'phrases_count':         '{total}项中练习了{n}项',
    'phrases_say_it':        '说出来：',
    'phrases_confirm':       '我们两人一起练习了这些短语',
    'mystery_next_clue':     '下一条线索 →',
    'mystery_confirm':       '我们一起解开了这个谜',
    'wallet_active_count':   '{n}个有效',
    'wallet_expires_day':    '{n}天后到期',
    'wallet_expires_days':   '{n}天后到期',
    'cap_solo_label':        '单人活动：已使用30%上限的{n}%',
    'cap_combined_label':    '合计(A+B)：已使用40%上限的{n}%',
    'joint_parent_label':    '家长',
    'joint_child_label':     '孩子',
    'parent_act_supporting': '支持{name}',
    'module_desc_a':         '完成这些单人活动，更好地支持您的孩子——并赚取折扣。',
    'module_desc_b':         '与{name}一起进行这些活动。双方必须确认才能解锁奖励。',
    'module_desc_c':         '帮助您的孩子养成现实生活中的好习惯。',
    'module_desc_d':         '横跨健康、创意、价值观和文化的扩展活动。',
  },
  'tr': {
    'progress_area_reading':   'Okuma',
    'progress_area_numeracy':  'Sayısal',
    'progress_area_writing':   'Yazma',
    'progress_area_wellbeing': 'İyi oluş',
    'progress_area_creative':  'Yaratıcı',
    'progress_area_science':   'Bilim',
    'snapshot_stars_label':   'Yıldızlar',
    'snapshot_correct_label': 'Doğru',
    'snapshot_streak_label':  'Gün serisi',
    'snapshot_help_maths':   'Evde birlikte nesneleri saymayı deneyin — küçük adımlar büyük özgüven inşa eder!',
    'snapshot_help_english': 'Her gün sadece 10 dakika birlikte sesli okumak büyük fark yaratır.',
    'snapshot_help_science': 'Evde basit deneyler yapın — bilim soruları canlanır!',
    'snapshot_help_general': 'Kitaplar, haritalar veya belgeseller aracılığıyla dünyayı keşfetmek genel bilgiyi hızla artırır.',
    'snapshot_weakest_suffix': 'en az doğru cevaba sahip.',
    'ai_chip_1': 'Özel ihtiyaçlı okuyuculara nasıl yardım ederim?',
    'ai_chip_2': 'KS2 matematik konularının en zorları hangileri?',
    'ai_chip_3': '5 yaş için bir etkinlik önerin',
    'tier_activities_month': 'Bu ay {n} etkinlik',
    'tier_next_label':       'Sıradaki:',
    'quiz_modal_progress':   '{total} sorudan {n}. soru',
    'quiz_modal_wrong':      'Cevap: {answer}',
    'quiz_modal_earned':     '{reward} kazandınız!',
    'article_modal_next':    'Sıradaki',
    'article_modal_finish':  'Bitir',
    'confirm_self_label':    'Bu etkinliği tamamladığımı onaylıyorum',
    'confirm_joint_label':   'İkimizin de tamamladığını onaylıyorum: {title}',
    'confirm_child_label':   'Çocuğum kendi bölümünü tamamladı',
    'reward_pill_both':      'Çocuk {n} yıldız kazanır · Siz kazanırsınız: {reward}',
    'claim_reward_close':    'Ödülü al ve kapat',
    'steps_confirm':         'İkimiz de bu yürüyüşü birlikte tamamladık',
    'checklist_found':       '{total} içinden {n} bulundu',
    'guided_step_label':     '{total} adımdan {n}. adım',
    'guided_confirm':        'Bu farkındalık seansını birlikte tamamladık',
    'text_label_drawing':    'Çocuğunuzun çizimini açıklayın ve başlık ekleyin:',
    'text_label_kind':       'Çocuğunuzun yaptığı iyi davranışı anlatın:',
    'text_confirm':          'İkimiz de bunun tamamlandığını onaylıyoruz',
    'story_confirm':         'Bu hikâyeyi birlikte yarattık',
    'story_preview_intro':   'Hikâyeniz: Bir zamanlar,',
    'rating_topic_label':    'Çocuğunuz size bunu öğretmeyi seçti:',
    'rating_confirm':        'Çocuğum bugün bana bu konuyu öğretti',
    'phrases_count':         '{total} içinden {n} alıştırıldı',
    'phrases_say_it':        'Söyleyin:',
    'phrases_confirm':       'İkimiz de bu ifadeleri birlikte alıştırdık',
    'mystery_next_clue':     'Sonraki ipucu →',
    'mystery_confirm':       'Bu gizemi birlikte çözdük',
    'wallet_active_count':   '{n} aktif',
    'wallet_expires_day':    '{n} gün içinde sona erer',
    'wallet_expires_days':   '{n} gün içinde sona erer',
    'cap_solo_label':        'Solo etkinlikler: %30 limitin %{n}\'i kullanıldı',
    'cap_combined_label':    'Birleşik (A+B): %40 limitin %{n}\'i kullanıldı',
    'joint_parent_label':    'Ebeveyn',
    'joint_child_label':     'Çocuk',
    'parent_act_supporting': '{name}\'i destekleme',
    'module_desc_a':         'Çocuğunuzu daha iyi desteklemek için bu solo etkinlikleri tamamlayın — ve indirimler kazanın.',
    'module_desc_b':         'Bu etkinlikleri {name} ile birlikte yapın. İkisi de onaylamalı.',
    'module_desc_c':         'Çocuğunuzun gerçek hayat alışkanlıkları oluşturmasına yardımcı olun.',
    'module_desc_d':         'İyi oluş, Yaratıcılık, Değerler ve Kültür alanlarında genişletilmiş etkinlikler.',
  },
  'so': {
    'progress_area_reading':   'Akhriska',
    'progress_area_numeracy':  'Xisaabta',
    'progress_area_writing':   'Qorista',
    'progress_area_wellbeing': 'Caafimaadka',
    'progress_area_creative':  'Hal-abuurka',
    'progress_area_science':   'Sayniska',
    'snapshot_stars_label':   'Xiddigaha',
    'snapshot_correct_label': 'Saxsan',
    'snapshot_streak_label':  'Silsilada maalmaha',
    'snapshot_help_maths':   'Isku day inaad wada tirirto waxyaabaha guriga — talaabooyinka yaryar waxay dhisaan kalsoonida weyn!',
    'snapshot_help_english': 'Akhriska cod dheer wada 10 daqiiqo maalintii waxay saameyn weyn yeeshaa.',
    'snapshot_help_science': 'Su\'aalaha sayniska way nool yihiin marka aad tijaabooyin fudud guriga ku sameyso!',
    'snapshot_help_general': 'Sahaminta adduunka iyada oo loo marayo buugaagta, khariidadaha ama filimada xogta ayaa si dhakhso ah u kordhiya aqoonta guud.',
    'snapshot_weakest_suffix': 'waxay leedahay ugu yaraan jawaabaha saxsan.',
    'ai_chip_1': 'Sideen u caawin karaa akhristayaasha baahida gaarka ah?',
    'ai_chip_2': 'Mawduucyada xisaabta ee ugu adag culusba?',
    'ai_chip_3': 'Ku talagal hawl da\'da 5',
    'tier_activities_month': '{n} hawlood bishan',
    'tier_next_label':       'Xigta:',
    'quiz_modal_progress':   'Su\'aal {n} ka mid ah {total}',
    'quiz_modal_wrong':      'Jawaabtu waa: {answer}',
    'quiz_modal_earned':     'Waad heshay {reward}!',
    'article_modal_next':    'Xiga',
    'article_modal_finish':  'Dhamee',
    'confirm_self_label':    'Waxaan xaqiijinayaa inaan dhamaystiray hawshan',
    'confirm_joint_label':   'Waxaan xaqiijinayaa inaan labadayadu dhamaystirnay: {title}',
    'confirm_child_label':   'Ilmahaygu wuxuu dhamaystiray qaybtii',
    'reward_pill_both':      'Ilmuhu wuxuu helaa {n} xiddig · Adna waxaad heshaa: {reward}',
    'claim_reward_close':    'Qaado abaalmarinta oo xidh',
    'steps_confirm':         'Labadayadu waan wadajir u dhamaystirnay socodkan',
    'checklist_found':       '{n} ka mid ah {total} la helay',
    'guided_step_label':     'Tallaabo {n} ka mid ah {total}',
    'guided_confirm':        'Waan wadajir u dhamaystirnay xaaladdan mindfulness',
    'text_label_drawing':    'Sharax sawirka ilmaha oo ku dar cinwaanka:',
    'text_label_kind':       'Sharax ficilka wanaagsan ee ay ilmuhu samaystay:',
    'text_confirm':          'Labadayadu waxaan xaqiijineynaa in tan la dhamaystiray',
    'story_confirm':         'Waan wadajir u abuurnay sheekadan',
    'story_preview_intro':   'Sheekadaada: Jiray markii hore,',
    'rating_topic_label':    'Ilmahagu wuxuu doorbiday inuu kuu baranjiyo:',
    'rating_confirm':        'Ilmahaygu maanta wuu ii baranjiray mawduucan',
    'phrases_count':         '{n} ka mid ah {total} la tababaray',
    'phrases_say_it':        'Dhaho:',
    'phrases_confirm':       'Labadayadu waan wadajir u tababarnay jumlaashan',
    'mystery_next_clue':     'Calaamadda xigta →',
    'mystery_confirm':       'Wadajir baan u xallinay qarsoodigan',
    'wallet_active_count':   '{n} firfircoon',
    'wallet_expires_day':    '{n} maalin ayay dhacaysaa',
    'wallet_expires_days':   '{n} maalmood ayay dhacaysaa',
    'cap_solo_label':        'Hawlaha kali-ah: {n}% ka mid ah xadka 30% la isticmaalay',
    'cap_combined_label':    'Wadarta (A+B): {n}% ka mid ah xadka 40% la isticmaalay',
    'joint_parent_label':    'Waalidka',
    'joint_child_label':     'Ilmaha',
    'parent_act_supporting': 'taageeridda {name}',
    'module_desc_a':         'Dhamee hawlahan kali-ah si aad u taageerso ilmahaaga si fiican.',
    'module_desc_b':         'Samee hawlahan wadajir ah ee {name}. Labaduba waa inay xaqiijiyaan si abaalmarinnada loo furo.',
    'module_desc_c':         'Caawi ilmahaaga inuu dhisto caadooyinka nolosha dhabta.',
    'module_desc_d':         'Hawlaha kordhiyay ee caafimaadka, hal-abuurka, qiimaha iyo dhaqanka.',
  },
}

ANCHOR = 'market_gap_6_desc'

with open('src/data/translations.js', 'r', encoding='utf-8') as f:
    content = f.read()

added = 0
for lang, keys in NEW_KEYS.items():
    # Find the anchor key in this language block
    anchor_str = f"  {ANCHOR}:"
    # Find the position after the anchor line's end
    lang_block_start = content.find(f"\n  {lang}:")
    if lang_block_start == -1:
        print(f"⚠️  Could not find lang block for {lang}")
        continue

    anchor_pos = content.find(anchor_str, lang_block_start)
    if anchor_pos == -1:
        print(f"⚠️  Anchor not found in {lang} block")
        continue

    # Find end of anchor line
    line_end = content.find('\n', anchor_pos)

    # Build insertion text
    insert_lines = []
    for k, v in keys.items():
        escaped = v.replace("'", "\\'")
        insert_lines.append(f"    {k}: '{escaped}',")

    insert_text = '\n' + '\n'.join(insert_lines)
    content = content[:line_end] + insert_text + content[line_end:]
    added += 1
    print(f"✅ Added {len(keys)} keys to {lang}")

with open('src/data/translations.js', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\nDone. Patched {added} language blocks.")

# Verify
import subprocess
result = subprocess.run(['node', '-e', "const t = require('./src/data/translations.js'); console.log('EN keys:', Object.keys(t.TRANSLATIONS.en).length);"], capture_output=True, text=True)
print(result.stdout.strip())
print(result.stderr.strip() if result.stderr.strip() else '')
